version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8082:8082"
    env_file:
      - ./backend/.env
