apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/white-proxy-434723-d6/distributed-project-app-frontend:latest
        ports:
        - containerPort: 80
        env:
          - name: REACT_APP_BASE_URL
            value: http://34.68.65.117 #Replace it with production backend ip before deployment