apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app-container
        image: gcr.io/white-proxy-434723-d6/distributed-project-app-backend:latest
        ports:
        - containerPort: 8082
        env:
        - name: CLOUD_SQL_HOST
          value: 127.0.0.1  # Connect to the Cloud SQL Proxy via localhost
        - name: CLOUD_SQL_DATABASE_NAME
          value: flask_app_db
        - name: CLOUD_SQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db_user
        - name: CLOUD_SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db_pass
        - name: SUBSCRIPTION_PATH
          valueFrom:
            secretKeyRef:
              name: pub-sub-credentials
              key: subscription_path
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secrets/gcp-pubsub-credentials/credentials.json
        volumeMounts:
        - name: gcp-pubsub-credentials
          mountPath: /secrets/gcp-pubsub-credentials
          readOnly: true


      # Cloud SQL Auth Proxy sidecar container
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.33.1
        command:
          - "/cloud_sql_proxy"
          - "-instances=white-proxy-434723-d6:us-east1:flask-app=tcp:3306"
          - "-credential_file=/secrets/cloudsql/credentials.json"
        ports:
          - containerPort: 3306
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true

      # Image Pull Secrets (if required)
      imagePullSecrets:
      - name: gcr-json-key

    # Define the volume that stores Cloud SQL Proxy credentials
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: gcp-sql-credentials
      - name: gcp-pubsub-credentials
        secret:
          secretName: gcp-pubsub-credentials